export type CreateHematologyDTO = {
  userId: string;
  clientId: number;
  hematology: Hematology;
};

export type CreateChemistryDTO = {
  userId: string;
  clientId: number;
  chemistry: Chemistry;
};

export type CreateClinicalMicroscopyDTO = {
  userId: string;
  clientId: number;
  clinicalmicroscopy: ClinicalMicroscopy;
};

export type CreateImmunologyDTO = {
  userId: string;
  clientId: number;
  immunology: Immunology;
};

export type CreateSerologyDTO = {
  userId: string;
  clientId: number;
  serology: Serology;
};

export type CreateSerologyHIVDTO = {
  userId: string;
  clientId: number;
  serologyHiv: SerologyHIV;
};

export type Chemistry = {
  fastingBloodSugarResult: string;
  fastingBloodSugarUnit: string;
  fastingBloodSugarRange: string;
  randomBloodSugarResult: string;
  randomBloodSugarUnit: string;
  randomBloodSugarRange: string;
  creatinineResult: string;
  creatinineUnit: string;
  creatinineRange: string;
  bloodUreaResult: string;
  bloodUreaUnit: string;
  bloodUreaRange: string;
  uricAcidResult: string;
  uricAcidUnit: string;
  uricAcidRange: string;
  sgptaltResult: string;
  sgptaltUnit: string;
  sgptaltRange: string;
  sgotastResult: string;
  sgotastUnit: string;
  sgotastRange: string;
  alkalinePhosphataseResult: string;
  alkalinePhosphataseUnit: string;
  alkalinePhosphataseRange: string;
  totalCalciumResult: string;
  totalCalciumUnit: string;
  totalCalciumRange: string;
  hbA1CResult: string;
  hbA1CUnit: string;
  hbA1Range: string;
  amylaseResult: string;
  amylaseUnit: string;
  amylaseRange: string;
  cholesterolResult: string;
  cholesterolUnit: string;
  cholesterolRange: string;
  triglyceridesResult: string;
  triglyceridesUnit: string;
  triglyceridesRange: string;
  hdlResult: string;
  hdlUnit: string;
  hdlRange: string;
  ldlResult: string;
  ldlUnit: string;
  ldlRange: string;
  vldlResult: string;
  vldlUnit: string;
  vldlRange: string;
  cholhdlRatioResult: string;
  cholhdlRatioUnit: string;
  cholhdlRatioRange: string;
  sodiumResult: string;
  sodiumUnit: string;
  sodiumRange: string;
  potassiumResult: string;
  potassiumUnit: string;
  potassiumRange: string;
  chlorideResult: string;
  chlorideUnit: string;
  chlorideRange: string;
  ionizedCalciumResult: string;
  ionizedCalciumUnit: string;
  ionizedCalciumRange: string;
  totalBilirubinResult: string;
  totalBilirubinUnit: string;
  totalBilirubinRange: string;
  directBilirubinResult: string;
  directBilirubinUnit: string;
  directBilirubinRange: string;
  indirectBilirubinResult: string;
  indirectBilirubinUnit: string;
  indirectBilirubinRange: string;
  totalProteinResult: string;
  totalProteinUnit: string;
  totalProteinRange: string;
  albuminResult: string;
  albuminUnit: string;
  albuminRange: string;
  globulinResult: string;
  globulinUnit: string;
  globulinRange: string;
  agRationResult: string;
  agRationUnit: string;
  agrAtionRange: string;
  oralGlucoseChallengeTestResult: string;
  oralGlucoseChallengeTestUnit: string;
  oralGlucoseChallengeTestRange: string;
  fbS50Result: string;
  fbS50Unit: string;
  fbS50Range: string;
  firstHour50Result: string;
  firstHour50Unit: string;
  firstHour50Range: string;
  fbS75Result: string;
  fbS75Unit: string;
  fbS75Range: string;
  firstHour75Result: string;
  firstHour75Unit: string;
  firstHour75Range: string;
  secondHour75Result: string;
  secondHour75Unit: string;
  secondHour75Range: string;
  fbS100Result: string;
  fbS100Unit: string;
  fbS100Range: string;
  firstHour100Result: string;
  firstHour100Unit: string;
  firstHour100Range: string;
  secondHour100Result: string;
  secondHour100Unit: string;
  secondHour100Range: string;
  thirdHour100Result: string;
  thirdHour100Unit: string;
  thirdHour100Range: string;
  twoHoursPostPrandialGlucoseResult: string;
  twoHoursPostPrandialGlucoseUnit: string;
  twoHoursPostPrandialGlucoseRange: string;
};

export type ClinicalMicroscopy = {
  micralResult: string;
  micralUnit: string;
  micralRange: string;
  urineColorResult: string;
  urineColorUnit: string;
  urineColorRange: string;
  urineTransparencyResult: string;
  urineTransparencyUnit: string;
  urineTransparencyRange: string;
  spGravityResult: string;
  spGravityUnit: string;
  spGravityRange: string;
  pHResult: string;
  pHUnit: string;
  pHRange: string;
  proteinResult: string;
  proteinUnit: string;
  proteinRange: string;
  glucoseResult: string;
  glucoseUnit: string;
  glucoseRange: string;
  bilirubinResult: string;
  bilirubinUnit: string;
  bilirubinRange: string;
  bloodResult: string;
  bloodUnit: string;
  bloodRange: string;
  leucocytesResult: string;
  leucocytesUnit: string;
  lucocytesRange: string;
  nitriteResult: string;
  nitriteUnit: string;
  nitriteRange: string;
  urobilinogenResult: string;
  urobilinogenUnit: string;
  urobilinogenRange: string;
  ketoneResult: string;
  ketoneUnit: string;
  ketoneRange: string;
  rbcResult: string;
  rbcUnit: string;
  rbcRange: string;
  wbcResult: string;
  wbcUnit: string;
  wbcRange: string;
  epithelialResult: string;
  epithelialUnit: string;
  epithelialRange: string;
  bacteriaResult: string;
  bacteriaUnit: string;
  bacteriaRange: string;
  mucusThreadResult: string;
  mucusThreadUnit: string;
  mucusThreadRange: string;
  hyalineCastResult: string;
  hyalineCastUnit: string;
  hyalineCastRange: string;
  fecalysisColorResult: string;
  fecalysisColorUnit: string;
  fecalysisConsistencyResult: string;
  fecalysisConsistencyUnit: string;
  fecalysisBloodResult: string;
  fecalysisBloodUnit: string;
  fecalysisMucusResult: string;
  fecalysisMucusUnit: string;
  fecalysisParasite: string;
  fecalysisFatGlobulesResult: string;
  fecalysisWBCResult: string;
  fecalysisWBCUnit: string;
  fecalysisRBCResult: string;
  fecalysisRBCUnit: string;
  urineHCGResult: string;
  urineHCGUnit: string;
  occultBloodResult: string;
  occultBloodUnit: string;
};

export type Hematology = {
  whiteBloodCellsResults: string;
  whiteBloodUnit: string;
  whiteBloodRange: string;
  redBloodCellsResults: string;
  redBloodUnit: string;
  redBloodRange: string;
  hemoglobinResults: string;
  hemoglobinUnit: string;
  hemoglobinRange: string;
  hematocritResult: string;
  hematocritUnit: string;
  hematocritRange: string;
  meanCorpuscularVolumeResult: string;
  meanCorpuscularVolumeUnit: string;
  meanCorpuscularVolumeRange: string;
  meanCorpuscularHbResult: string;
  meanCorpuscularHbUnit: string;
  meanCorpuscularHbRange: string;
  meanCorpuscularHbConcResult: string;
  meanCorpuscularHbConcUnit: string;
  meanCorpuscularHbConcRange: string;
  rbcDistributionWidthResult: string;
  rbcDistributionWidthUnit: string;
  rbcDistributionWidthRange: string;
  plateletCountResult: string;
  plateletCountUnit: string;
  plateletCountRange: string;
  segmentersNeutrophilsResult: string;
  segmentersNeutrophilsUnit: string;
  segmentersNeutrophilsRange: string;
  lymphocytesResult: string;
  lymphocytesUnit: string;
  lymphocytesRange: string;
  monocytesResult: string;
  monocytesUnit: string;
  monocytesRange: string;
  eosinophlisResult: string;
  eosinophlisUnit: string;
  eosinophlisRange: string;
  basophilsResult: string;
  basophilsUnit: string;
  basophilsRange: string;
  bandsResult: string;
  bandsUnit: string;
  bandsRange: string;
  metamyelocytesResult: string;
  metamyelocytesUnit: string;
  metamyelocytesRange: string;
  myelocytesResult: string;
  myelocytesUnit: string;
  myelocytesRange: string;
  promyelocytesResult: string;
  promyelocytesUnit: string;
  promyelocytesRange: string;
  blastCellsResult: string;
  blastCellsUnit: string;
  blastCellsRange: string;
  absoluteSegNeutroCountResult: string;
  absoluteSegNeutroCountUnit: string;
  absoluteSegNeutroCountRange: string;
  absoluteLymphocyteCountResult: string;
  absoluteLymphocyteCountUnit: string;
  absoluteLymphocyteCountRange: string;
  absoluteMonocyteCountResult: string;
  absoluteMonocyteCountUnit: string;
  absoluteMonocyteCountRange: string;
  absoluteEosinophilCountResult: string;
  absoluteEosinophilCountUnit: string;
  absoluteEosinophilCountRange: string;
  absoluteBasophilCountResult: string;
  absoluteBasophilCountUnit: string;
  absoluteBasophilCountRange: string;
  absoluteBandCountResult: string;
  absoluteBandCountUnit: string;
  absoluteBandCountRange: string;
  clottingTimeResult: string;
  clottingTimeRange: string;
  bleedingTimeResult: string;
  bleedingTimeRange: string;
  esrResult: string;
  esrUnit: string;
  esrRange: string;
  bloodTypeResult: string;
  posNegBloodType: string;
};

export type Immunology = {
  tshResult: string;
  tshUnit: string;
  tshRange: string;
  ftFourResult: string;
  ftFourUnit: string;
  ftFourRange: string;
  ccpIgGResult: string;
  ccpIgGUnit: string;
  ccpIgGRange: string;
  psaResult: string;
  psaUnit: string;
  psaRange: string;
  ftThreeResult: string;
  ftThreeUnit: string;
  ftThreeRange: string;
  tThreeResult: string;
  tThreeUnit: string;
  tThreeRange: string;
  tFourResult: string;
  tFourUnit: string;
  tFourRange: string;
  proBNPResult: string;
  proBNPUnit: string;
  proBNPRange: string;
};

export type GetIncrementedDTO = {
  latestId: number;
};

export type GetClientDetailsResultDTO = {
  userId: string;
  clientId: number;
  chemId: number;
  clinicId: number;
  hemaId: number;
  immuId: number;
  serologyHIVId: number;
  serologyId: number;
  fullName: string;
};

export type Serology = {
  antiHCVScreeningResult: string;
  antiHCVScreeningRemarks: string;
  antiHCVScreeningMethod: string;
  antiHavIgGScreeningResult: string;
  antiHavIgGScreeningRemarks: string;
  antiHavIgGScreeningMethod: string;
  vdrlSyphilisResult: string;
  vdrlSyphilisRemarks: string;
  vdrlSyphilisMethod: string;
  hBsAgScreeningResult: string;
  hBsAgScreeningRemarks: string;
  hBsAgScreeningMethod: string;
  antiHavIgMScreeningResult: string;
  antiHavIgMScreeningRemarks: string;
  antiHavIgMScreeningMethod: string;
  nsOneResult: string;
  nsOneMethod: string;
  igGResult: string;
  igGMethod: string;
  igMResult: string;
  igMMethod: string;
  serumHCGResult: string;
  salmonellaIgGResult: string;
  salmonellaIgGUnit: string;
  salmonellaIgMResult: string;
  salmonellaIgMMethod: string;
  antiHBSResult: string;
  antiHBSMethod: string;
  serumPlasmaHCGResult: string;
  serumPlasmaHCGMethod: string;
};

export type SerologyHIV = {
  hivRapidDiagnosticTestResult: string;
  hivRapidDiagnosticTestMethod: string;
  kitUsed: string;
  kitExpiry: string;
  kitLotNumber: string;
  diluentLotNumber: string;
  kitReferenceNumber: string;
  remarks: string;
};
